on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # test:
  #   runs-on: ubuntu-24.04

  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Run tests
  #       run: |
  #         set -e
  #         docker compose -f docker-compose.test.yml up --build --abort-on-container-exit

  #     - name: Cleanup
  #       if: always()
  #       run: docker compose -f docker-compose.test.yml down

  deploy:
    runs-on: ubuntu-24.04
    # needs: test

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            set -e
            cd AcadyoquizzV2-front-deploy
            git pull
            docker compose down
            docker compose up -d --build
            echo "✅ Déploiement terminé !"
